name: glistadmin
version: '0.1'
summary: A modern listadmin for mailman
description: |
    This will read your current listadmin configuration file (not all options
    are supported yet), and has a somewhat similar behaviour.

grade: stable
confinement: strict

parts:
  gla:
    source: .
    plugin: python
    python-version: python2
    requirements: requirements.txt
    stage-packages:
        - python-gtk2
    after: [desktop-gtk2]

apps:
    glistadmin:
        command: desktop-launch $SNAP/bin/glistadmin
        plugs: [x11, home, network, network-control, mount-observe]
